### ISSUE TITLE
404 Returned when publishing new chart

### ISSUE THREAD

**Issue by mshigekawa** [methnen/m-chart#87] opened 2017-02-02 03:19 UTC
With Wordpress 4.7.2 on a Multisite install, when you create a new chart and view the auto generated page, a 404 error is returned on the new page.

**Steps**
1) Add Chart
2) Enter values manually into chart
3) Click Publish
4) View new page 
404 Not Found error returned

**Workaround**
1) Copy the chart short code (ie [chart id="30053"])
2) Paste it into a new blank page
The chart display successfully in the new page

**Comment by methnen** [comment] 2017-02-02 03:23
Hello @mshigekawa that's actually by design currently though I could add something in that filters the content function. I'll have to look into adding that. If you want them to not 404 you would need to include a single-m-chart.php template with the correct method in the template. I get why it's confusing though. It's something I should tweak in any case.

**Comment by mshigekawa** [comment] 2017-02-02 03:32
Oh gotcha. For my use case that deals with websites for personal trainers I'm looking to have personal trainers enter their client's measurements into the table then was hoping they could just click publish and share that page with their clients (instead of having to create a separate page and manually add the shortcode).

What method do I need to add in the single-m-chart.php for this use case?

**Comment by methnen** [comment] 2017-02-02 17:43
You'd just include this in the template where you want the chart to show:

```php
<?php m_chart()->get_chart(); ?>
```

**Comment by methnen** [comment] 2017-02-22 19:34
Closing as relevant issue is addressed in 1.6.

**Closed by methnen** 2017-02-22 19:34 UTC
Labels: bug, enhancement

**Comment by mshigekawa** [comment] 2017-02-24 02:10
Just updated to 1.6. Was hoping my clients could now just press Publish in Charts and it would generate a new page with the included chart, but that doesn't appear to be the case...

**Comment by methnen** [comment] 2017-02-24 02:33
Hey @mshigekawa I tested this in the default WP them and a few others just to be sure and it was working fine. Two thoughts:

1. Perhaps there's an issue with the theme?
2. Maybe your permalinks need to be rebuilt?
