### ISSUE TITLE
Can't publish chart

### ISSUE THREAD

**Issue by Inquaery** [methnen/m-chart#117] opened 2018-08-25 09:08 UTC
Latest WP and latest Mchart. As soon as values are written into table publish button becomes inactive.

**Comment by methnen** [comment] 2018-08-27 15:04
@Inquaery I think I've duplicated this one. There's a learning curve to Chart.js that I'm still on apparently. I'll work on getting a fix in ASAP.

**Comment by methnen** [comment] 2018-08-27 23:49
@Inquaery I've pushed what a fix for this (1.7.3). Can you let me know if this does/doesn't fix the issue you were having?

**Comment by Inquaery** [comment] 2018-08-29 16:06
It does not fix the issue. It is the same wheater is Highsharts or chart.js.

**Comment by methnen** [comment] 2018-08-29 16:14
Hmm... then I'm not seeing what you're seeing. Is there any way I could see it in action on your install?

**Comment by philooo2** [comment] 2018-09-20 16:41
Same here, the graph doesn't populate and I get a console error 

looking at the network list I also don't see anything loading the char.js or bundle-chart.js


```
Uncaught ReferenceError: Chart is not defined
    at Object.m_chart_chartjs_13_1.render_chart (post.php?post=13&action=edit:525)
    at HTMLDocument.<anonymous> (post.php?post=13&action=edit:532)
    at i (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=4.9.8:2)
    at Object.fireWith [as resolveWith] (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=4.9.8:2)
    at Function.ready (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=4.9.8:2)
    at HTMLDocument.K (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,utils&ver=4.9.8:2)

```

**Comment by methnen** [comment] 2018-09-20 16:45
@philooo2 is there any chance you can get me access to your WP install to look into this? Since I can't duplicate this issue on my end (I've tried extensively with no luck) I'm really unable to do much without being able to play with it in an install that has it happening.

**Comment by philooo2** [comment] 2018-09-20 16:46
> @philooo2 is there any chance you can get me access to your WP install to look into this? Since I can't duplicate this issue on my end (I've tried extensively with no luck) I'm really unable to do much without being able to play with it in an install that has it happening.

I'll email you one right now

**Comment by gibbsyns3** [comment] 2018-10-28 22:50
hello meth

any progress on this. i'm getting similar to inquaery's original post, though i'm not getting the publish/save as draft when i enter data into the table, for me it is disabled as soon as the new chart screen opens. 

the list of charts is showing those i've attempted to create - all at draft and all showing only the chart title i have applied. none of the data i have added or imported is showing. 

thanks

**Comment by methnen** [comment] 2018-10-29 16:33
Hey @gibbsyns3 I've made no progress. The ticket did help me discover an unrelated issue but since I can't duplicate this locally and people with the issue keep going incommunicado I've been unable to track down what's going on.

Is there any way you can give me access to the install where this is occurring? If so I would be delighted to chase this down and figure out what the problem is.

As always my personal email is jamie AT methnen.com if you'd like to email any relevant information to me privately.

**Comment by methnen** [comment] 2018-11-01 22:15
Just a note to everyone on this thread. I pushed an update (1.7.5) with a few more bug fixes that might solve what was happening here though since I've never been able to duplicate the issue I can't say for sure.

**Comment by methnen** [comment] 2019-02-13 15:34
Again there's been no follow up no this and now further reports of the same/similar issue so I'm hoping it's been fixed in the more recent releases.

**Closed by methnen** 2019-02-13 15:34 UTC
