### ISSUE TITLE
Cannot read property 'chart' of undefined

### ISSUE THREAD

**Issue by heyaitsa** [methnen/m-chart#121] opened 2018-10-08 08:28 UTC
Reposted from here: https://github.com/methnen/m-chart-highcharts-library/issues/10.

Hi, I'm currently using the latest version of M-Chart (1.7.4). The Chart does not appear at all and does not update, I checked in the console and this is what shows. If you could help me look into it that would be great thanks a lot.

`Uncaught TypeError: Cannot read property 'chart' of undefined
at HTMLCanvasElement.m_chart_chartjs_admin.refresh_chart (m-chart-chartjs-admin.js:115)
at HTMLCanvasElement.dispatch (load-scripts.php:3)
at HTMLCanvasElement.r.handle (load-scripts.php:3)
at Object.trigger (load-scripts.php:3)
at Object.a.event.trigger (load-scripts.php:9)
at HTMLCanvasElement.<anonymous> (load-scripts.php:3)
at Function.each (load-scripts.php:2)
at a.fn.init.each (load-scripts.php:2)
at a.fn.init.trigger (load-scripts.php:3)
at Object.<anonymous> (m-chart-admin.js:484)`

**Comment by methnen** [comment] 2018-10-11 14:33
@heyaitsa no other plugins? What browser are you using?

**Comment by heyaitsa** [comment] 2018-10-12 07:43
No other plugins, no theme, I'm using Version 69.0.3497.100 of Google Chrome (64bit).

**Comment by methnen** [comment] 2018-10-12 15:58
I've tested that exact configuration and it's working fine for me. :( This has been a frustrating issue to try and diagnose without being able to observe it.

You must have a them active though. You can't not have one. I'm assuming it's just the default though. I've tried all three of the ones installed by default and that doesn't reproduce the issue.

Are you in a particular language? Just trying to think of what might be causing this.

And you installed the plugin from the wordpress.org/plugins or through the admin panel in your install correct?

**Comment by methnen** [comment] 2019-02-13 15:33
Closing since the OP quit following up.

**Closed by methnen** 2019-02-13 15:33 UTC
