### ISSUE TITLE
SELECT FILE not working..unable to load data..

### ISSUE THREAD

**Issue by bostonmacosx** [methnen/m-chart#174] opened 2023-02-20 20:08 UTC
When I choose the SELECT FILE..nothing happens...so unable to load data into the plugin....head scratching...

6.1.1 Wordpress...

<img width="1071" alt="Screen Shot 2023-02-20 at 3 07 33 PM" src="https://user-images.githubusercontent.com/12223407/220190449-31a6c570-d7e7-4ce9-bc04-5e52a99d559a.png">

**Comment by methnen** [comment] 2023-02-20 21:23
It looks like the file isn't making it into the import script somehow. That layout looks weird as well. Can you check and see if there's any Javascript errors in the console?

**Comment by bostonmacosx** [comment] 2023-02-20 22:06
@methnen 
A Bunch

<img width="1026" alt="Screen Shot 2023-02-20 at 5 06 19 PM" src="https://user-images.githubusercontent.com/12223407/220205234-7cd518e7-e351-4be3-ba8b-73261ed40039.png">

**Comment by methnen** [comment] 2023-02-20 22:23
OK, yeah, that's gonna cause problems. :)

Those urls don't look strange at all, I'm not sure why they'd all return connection refused. 

I see they're non SSL links but that's not too unusual given it's a local dev setup.

I think the issue is likely the missing port in the URLs.

Can you try this?

Open the class-m-chart.php file and look for the plugin_url function and replace it with this one:

```php
/**
 * VIP's CDN was breaking Highcharts ability to handle embedded SVGs so this should circumvent that
 * If you wanted to say, watermark your charts, SVGs suddenly become very important
 *
 * @param string $path option additional path to be used (e.g. components)
 *
 * @return string URL to the plugin directory with path if parameter was passed
 */
public function plugin_url( $path = '' ) {
	if ( is_admin() ) {
		$url_base = parse_url( admin_url() );
	}
	else
	{
		$url_base = parse_url( home_url() );
	}

	$url_path = parse_url( plugins_url( $path, __DIR__ ) );

	// Check for a port value if one exists we make sure it's honored
	$port = '';

	if ( isset( $url_base['port'] ) && 80 != $url_base['port'] ) {
		$port = ':' . $url_base['port'];
	}

	return $url_base['scheme'] . '://' . $url_base['host'] . $port . preg_replace( '#/$#', '', $url_path['path'] ) . ( empty( $url_path['query'] ) ? '' : '?' . $url_path['query'] );
}
```

See if that fixes the issue?

**Comment by bostonmacosx** [comment] 2023-02-20 22:32
Better however hte actual post of data is stil lnot working...interface looks more healthy...

<img width="1721" alt="Screen Shot 2023-02-20 at 5 31 45 PM" src="https://user-images.githubusercontent.com/12223407/220207701-c41d9953-e568-45d9-8f39-0b0d94e801fd.png">

**Comment by bostonmacosx** [comment] 2023-02-20 22:35
ok got it....so the issue was I was using a chart that when build was missing the "table" at the top due to the bad URLs....so it was preventing the import of the CSV..so I destroyed all the charts and started over and appears to be woring now..

**Comment by methnen** [comment] 2023-02-20 22:38
Ah, cool. 

Yeah, I was looking at the code that was failing and wasn't finding anything that seemed likely as an issue.

Glad you got it working.

The fix for the port thing will be in the next release.

**Closed by methnen** 2023-02-20 22:38 UTC
